# Generated by Django 3.0.5 on 2020-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200706_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='img1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
